services:
  microservice:
    image: ghcr.io/bozonx/free-llm-router-microservice:latest
    container_name: free-llm-router-microservice
    hostname: free-llm-router-microservice
    restart: unless-stopped
    user: '1000:1000'
    ports:
      - '8080:8080'
    environment:
      - TZ=UTC
      - LOG_LEVEL=warn
    volumes:
      - ../config.yaml:/app/config.yaml:ro
      #- ../models.yaml:/app/models.yaml:ro
    healthcheck:
      test: [ 'CMD-SHELL', 'wget -qO- http://127.0.0.1:8080/api/v1/health || exit 1' ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
